#!/bin/sh

shadow="/etc/shadow"
root_hash='$6$r2s$mVFaCW7YUjMrjnSrtPFYZsdppRR79FLTWGZ5vXKTLVsBg7FYM31IGVbvELvjQ0OhyesAPJM5wGnWrcPyKVfW31'

current_hash="$(sed -n 's/^root:\([^:]*\):.*/\1/p' "$shadow")"

if [ -z "$current_hash" ]; then
	sed -i "s#^root:[^:]*:#root:${root_hash}:#" "$shadow"
fi

exit 0
