#!/bin/sh

uci -q get system.@imm_init[0] > /dev/null || uci -q add system imm_init > /dev/null

default_mirror="https://mirrors.pku.edu.cn/immortalwrt"
apk_mirror="$(uci -q get system.@imm_init[0].apk_mirror)"

case "$apk_mirror" in
	""|"https://mirrors.vsean.net/openwrt"|"https://mirrors.vsean.net/immortalwrt")
		apk_mirror="$default_mirror"
		uci -q batch <<-EOF
			set system.@imm_init[0].apk_mirror="$apk_mirror"
			commit system
		EOF
		;;
esac

feeds="/etc/apk/repositories.d/distfeeds.list"
if [ -f "$feeds" ]; then
	sed -i.bak \
		-e "s#https://mirrors.vsean.net/openwrt#$apk_mirror#g" \
		-e "s#https://mirrors.vsean.net/immortalwrt#$apk_mirror#g" \
		-e "s#https://downloads.immortalwrt.org#$apk_mirror#g" \
		"$feeds"
fi

exit 0
